environment:
  hosts:
    - "dev.next-framework.com"
  debug:
    enabled: true
  database:
    main:
      hostname: localhost
      database: nextframework_default
      username: root
      password: toor
      connector: mysql
      charset: utf8
  modules:
    - core
    - test